services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecom-latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:alpine
    container_name: postgres-latest
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db-data:/val/lib/postgresql/data
      
  redis:
    image: redis:latest
    container_name: redis-latest
    env_file:
      - .env
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    volumes:
      - redis-data:/var/lib/redis
    ports:
      - 6379:6379

volumes:
  db-data:
  redis-data: